apiVersion: v1
kind: Namespace
metadata:
  name: fgarrido
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-config
  namespace: fgarrido
data:
  USERNAME: "username_devops"
---
apiVersion: v1
kind: Secret
metadata:
  name: devops-secret
  namespace: fgarrido
type: Opaque
stringData:
  API_KEY: "key_api"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-test
  namespace: fgarrido
  labels:
    app: backend-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-test
  template:
    metadata:
      labels:
        app: backend-test
    spec:
      containers:
        - name: backend
          image: francogbb/backend-test
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: USERNAME
              valueFrom:
                configMapKeyRef:
                  name: devops-config
                  key: USERNAME
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: devops-secret
                  key: API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: devops-service
  namespace: fgarrido
  labels:
    app: backend-test
spec:
  selector:
    app: backend-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP